name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: create dir
      run: mkdir reports
    - name: see path
      run: pwd
    - name: docker create volume
      run: docker volume create --name myvol --opt type=none --opt device="/home/runner/work/postmanNewmanExample/postmanNewmanExample/reports" --opt o=bind
    - name: Build the Docker image
      run: docker build . -t newman
    - name: Run docker container
      run: docker run -v myvol:/newman newman
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
          name: test report
          path: |
            /home/runner/work/postmanNewmanExample/postmanNewmanExample/reports
